# Generated by Django 3.1.2 on 2020-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Introduce el nombre del género')),
                ('href', models.TextField(help_text='url para acceder en goodreads')),
            ],
        ),
    ]
