# Generated by Django 3.1.2 on 2020-12-25 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201224_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fechapublicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librosnuevosgeneros',
            name='ultimaactualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
