# Generated by Django 3.1.2 on 2020-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201225_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='href',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
