# Generated by Django 3.1.2 on 2020-12-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_libro_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosLeidosSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimaactualizacion', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genero')),
                ('libros', models.ManyToManyField(to='books.Libro')),
            ],
        ),
    ]
