# Generated by Django 3.1.2 on 2020-12-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_librosleidossemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='href',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='TodosTusLibros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.TextField()),
                ('url_libro', models.URLField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.libro')),
            ],
        ),
    ]
