# Generated by Django 3.1.2 on 2020-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201226_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='todostuslibros',
            name='urlCompra',
            field=models.URLField(default='ahora'),
            preserve_default=False,
        ),
    ]
