# Generated by Django 3.1.2 on 2020-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_todostuslibros_urlcompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroVotado',
            fields=[
                ('isbn', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('anyopublicacion', models.TextField()),
                ('urlImg', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVotante',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
