# Generated by Django 3.1.2 on 2020-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_librousuariorating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovotante',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
