# Generated by Django 3.1.2 on 2020-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201227_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='todostuslibros',
            name='categorias',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
