# Generated by Django 3.1.2 on 2020-12-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_todostuslibros_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todostuslibros',
            name='fechapublicacion',
            field=models.DateTimeField(),
        ),
    ]
