# Generated by Django 3.1.2 on 2020-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20201229_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovotante',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
