# Generated by Django 3.1.2 on 2021-01-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20201230_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todostuslibros',
            name='categorias',
        ),
    ]
