# Generated by Django 3.1.2 on 2021-01-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_planetalibros_tematicas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tematicas',
        ),
    ]
